# PostgreSQL Database Configuration (Cloud / Render)
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d8e3hckp3tds7385nb40-a.oregon-postgres.render.com/smartbank_db_dcae?sslmode=require}
spring.datasource.username=${DB_USERNAME:smartbank_db_dcae_user}
spring.datasource.password=${DB_PASSWORD:lKAnm12sOi1kSLjE0v9gVivNEpQ7aAJr}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
