spring.application.name=SmartBank
spring.profiles.active=dev


# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Server Configuration
server.port=8080
server.servlet.context-path=/smartbank

# Logging
logging.level.root=INFO
logging.level.com.smartbank=DEBUG
logging.level.org.springframework.security=DEBUG
