# PostgreSQL Database Configuration (Cloud / Render)
spring.datasource.url=jdbc:postgresql://dpg-d8e3hckp3tds7385nb40-a.oregon-postgres.render.com/smartbank_db_dcae?sslmode=require
spring.datasource.username=smartbank_db_dcae_user
spring.datasource.password=lKAnm12sOi1kSLjE0v9gVivNEpQ7aAJr
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
